@extends('shared.master')

@section('title', 'Kalimbe')

@section('content')
<div class="alice-bg section-padding-bottom">
      <div class="container no-gliters">
        <div class="row no-gliters">
          <div class=" col-md-12 col-lg-12 col-sm-12">
            <div class="terms-container">
              <div class="terms-content-wrapper" style="width:100%">
                <div class="policy-tab">
                  <ul class="nav nav-tabs" id="myTab" role="tablist">
                    <li class="nav-item">
                      <a class="nav-link active" id="privacy-tab" data-toggle="tab" href="#privacy" role="tab" aria-controls="privacy" aria-selected="true">Conditions générales d’Utilisation des candidats</a>
                    </li>
                  </ul>
                  <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="privacy" role="tabpanel" aria-labelledby="privacy-tab">
                      <h4 id="welcome">Introduction</h4>
                      <p>Ce document précise les Conditions générales d’Utilisation auxquelles tout candidat est autorisé à utiliser les sites et les services de Kalimbè. Ces conditions représentent un accord contraignant entre les candidats et le groupe Youmann Consulting qui exploite le site web auquel vous accédez (« Kalimbè »). Vous acceptez ces conditions chaque fois que vous accédez au site ou utilisez les services de Kalimbè. N’utilisez pas les sites ou les services de Kalimbè si vous n’acceptez pas les conditions présentées ici. Kalimbè peut modifier les Conditions en mettant en ligne une version actualisée de cette page web. Vous devez visiter régulièrement cette page et lire les conditions, car elles sont légalement contraignantes pour vous. Kalimbè s’autorise à suspendre ou supprimer les accès des candidats qui ne respecteraient pas les présentes conditions. Vous devez avoir 16 ans ou plus pour pouvoir visiter ou utiliser les sites de Kalimbè. Si vous avez moins de 16 ans ou êtes mineur dans votre juridiction, vous devez utiliser les sites de Kalimbè sous la supervision d’un parent, d’un responsable légal ou un autre adulte responsable.</p>
                     
                      <h5 id="termss">1. Utilisation des contenus de Kalimbè.</h5>
                      <p>Kalimbè vous autorise, selon les présentes conditions à accéder et utiliser les sites de kalimbè et leur contenu (comme défini ci-dessous) pour télécharger et imprimer lesdits contenus qui sont disponibles sur ou à partir des sites de Kalimbè et ceci exclusivement pour une utilisation privée, non commerciale.</p>
                      <p>Les contenus, par exemple des designs, textes, graphiques, images, vidéos, informations, logos, icônes-boutons, logiciels, fichiers audio et autres (rassemblés sous le terme « contenus de Kalimbè » sont protégés par copyright, la protection des marques commerciales déposées et autres lois.</p>
                      <p>Une utilisation non autorisée des contenus peut violer ces lois et/ ou les réglementations et est strictement interdite. Vous devez conserver toutes les copies autorisées que vous avez faites de « contenus de Kalimbè », toutes les informations soumises aux droits d’auteur, et autres informations propriétaires dans les contenus d’origine de Kalimbè.</p>
                      <p>Tout code créé par Kalimbè pour générer ou afficher des contenus de Kalimbè ainsi que les pages dont sont faits les sites de Kalimbè, est également protégé par copyright et vous ne devez pas copier ou modifier ces codes.</p>
                      <p>Vous vous engagez à ne pas vendre, modifier, reproduire, afficher, distribuer ou autrement utiliser le Contenu du Site que ce soit à des fins commerciales ou non, publiquement ou en privé, notamment si cette utilisation a pour but de promouvoir des produits ou services qui ne sont pas ceux de Kalimbè, dénigrer ou discréditer Kalimbè ou de ses concédants de licence ou encore porterait atteinte à la propriété intellectuelle de Kalimbè ou ses concédants. L’interdiction ci-devant est valable quelque soit le support, en ce compris tout autre site web, application ou environnement informatique en réseau. Tout code créé par Kalimbè, pour produire ou afficher du Contenu ou des pages composant une application ou un service, est également protégé par le droit d’auteur de Kalimbè. Il est interdit de copier, adapter ou altérer ces codes.</p>
                     
                      <h5 id="condition">2. Utilisation des Services de Kalimbè.</h5>
                      <p>Les publications d’offre, et les autres fonctions des sites de Kalimbè ne peuvent être utilisées que par des personnes recherchant un emploi et/ou des informations de carrière. En cas de conflit entre les présentes Conditions et contrat que vous pourriez avoir avec Kalimbè, les termes de votre contrat prévaudront. Le terme « publier », mentionné aux présentes, signifie la soumission, la publication ou l’affichage de données par vous sur un site de Kalimbè.</p>
                      <p>Les candidats s’interdisent de :</p>

                      <p>(a) transmettre, publier, distribuer, enregistrer ou détruire tout matériel, en particulier les contenus de Kalimbè, en violation des lois ou règlementations en vigueur concernant la collecte, le traitement ou le transfert d’informations personnelles, ou en violation des directives de protection des informations de Kalimbè ;</p>
                      <p>(b) d’effectuer des actions qui représenteraient une contrainte non raisonnable ou disproportionnée pour l’infrastructure du site web de Kalimbè ;</p>
                      <p>(c) d’utiliser un autre logiciel de navigation ou de recherche que les outils disponibles sur le site Kalimbè, les navigateurs web tiers généralement disponibles de tiers ou autres outils autorisés par Kalimbè ;</p>
                      <p>(d) utiliser des systèmes d’exploration de données (data mining), des robots ou toute autre méthode semblable pour la collecte et l’exploitation de données ;</p>
                      <p>(e) de mettre en danger ou essayer de mettre en danger la sécurité d’un site web de Kalimbè. Cela comprend les tentatives de contrôler, scanner ou tester la vulnérabilité d’un système ou réseau ou de violer des mesures de sécurité ou d’authentification sans une autorisation préalable expresse ;</p>
                      <p>(f)  contrefaire les protocoles TCP/IP ou toute partie des données d’en-tête de mail ou de publication sur un forum ;</p>
                      <p>(g)  d’effectuer une ingénierie inversée (Reverse Engineering) ou une décompilation de pages web de Kalimbè ;</p>
                      <p>(h) agréger, copier ou dupliquer de quelque manière que ce soit le Contenu ou les informations disponibles sur les sites Kalimbè, en ce compris les d’offres d’emploi expirées, sauf dûment autorisé par les présentes Conditions ;</p>
                      <p>(i) référencer ou créer des liens vers tout Contenu ou information disponible depuis les sites de Kalimbè, sauf expressément autoriser par les présentes Conditions ;</p>
                      <p>(j) Publier des contenus ou des matériels qui contiennent des informations fausses ou induisant en erreur ou qui promeuvent, soutiennent ou renforcent des activités qui sont interdites par ces conditions. Par exemple la fabrication ou l’achat d’armes illégales, des violations de la vie privée, la préparation ou l’introduction de virus informatiques ou de copies piratées ;</p>
                      <p>(k) de publier un CV, un Profil ou de poser sa candidature pour un poste au nom d’une autre personne;</p>
                      <p>(l) divulguer à tout agent, agence ou autre tiers, le contact d’un employeur ;</p>
                      <p>(m) rendre publique plus d’une copie d’un même CV à la fois ;</p>
                      <p>(n) partager, avec un tiers, toute identification de connexion aux sites Kalimbè, un tiers étant toute personne autre que le candidat unique auquel est affecté l’identifiant ;</p>
                      <p>(o) obtenir des données ne vous étant pas destinées ou se connecter à un serveur ou un compte pour lequel vous n’êtes pas autorisé ;</p>
                      <p>(p) publier ou soumettre sur les sites Kalimbè une information biographique incomplète, fausse, inexacte ou appartenant à un tiers ;</p>
                      <p>(q) de publier un contenu qui contient des pages à accès restreint, protégé par mot de passe ou des pages web ou images masquées ;</p>
                      <p>(r) obtenir d’autres utilisateurs des mots de passe ou des données personnelles d’identification ;</p>
                      <p>(s) supprimer ou modifier tout élément publié par une autre personne ou entité ;</p>
                      <p>(t) harceler, inciter au harcèlement ou prôner le harcèlement à l’encontre d’un groupe, d’une entreprise ou d’une personne ;</p>
                      <p>(u) envoyer des courriers, mails ou fax ou effectuer des appels téléphoniques non sollicités, notamment pour promouvoir des produits ou services, à tout utilisateur ou tenter de contacter ces derniers sans avoir obtenu au préalable leur accord ;</p>
                      <p>(v) tenter d’interférer avec le service fourni à tout utilisateur, hébergeur ou réseau, au moyen notamment d’un téléchargement de virus informatique, d’une surcharge, de « flooding », « spamming », « mailbombing » ou « crashing » ;</p>
                      <p>(w) répandre ou encourager la copie illégale ou non autorisée du travail d’un tiers protégé par des droits d’auteur, tels que le transfert ou la mise à disposition de logiciels piratés ou leurs liens, fournir ou mettre à disposition des renseignements permettant de contourner des dispositifs de protection des œuvres couvertes par des droits d’auteurs, ou fournir ou mettre à disposition de la musique, vidéo ou autres médias et liens vers des sites de piratage ;</p>
                      <p>(x) utiliser les Services Kalimbè à des fins illicites ou pour les besoins d’une activité illégale, publier ou soumettre tout contenu ou CV diffamatoire, calomnieux, implicitement ou explicitement offensant, vulgaire, obscène, menaçant, abusif, haineux, raciste, discriminatoire, à tendance menaçante ou pouvant troubler, gêner, provoquer de l’anxiété, harceler tout individu ainsi que d’ incorporer des liens vers du contenu pornographique, à connotation sexuelle ou contraire aux bonnes mœurs; ou mettre en ligne un CV autre qu’un réel CV et qui aurait pour but de promouvoir des produits ou services.</p>
                      <p>(Y) Des violations de la sécurité du système ou du réseau peuvent conduire à des poursuites civiles et pénales. Kalimbè recherchera les occasions dans lesquelles de telles violations pourraient avoir eu lieu et peut faire appel aux autorités judiciaires pour poursuivre des candidats qui ont participé à de telles violations et coopérer avec ces autorités.</p>
                      <p>(z) Il est de votre responsabilité de conserver la confidentialité de votre compte Employeur, du profil et des mots de passe. Il vous est interdit de partager même temporairement, vos identifiants, mots de passe et autres paramètres d’accès à votre compte à des tiers. Vous êtes responsable pour l’utilisation de vos enregistrements et mots de passe sur les sites de Kalimbè, que cette utilisation ait été autorisée ou pas par vous. A ce titre, vous vous obligez à informer Kalimbè, sans délai, de toutes utilisations non autorisées de son compte et /ou identifiants.</p>
                      
                      <h5 id="privacy-2">3. Conditions additionnelles.</h5>
                      <p>Lorsque vous vous inscrivez sur le Site, il vous sera demandé de fournir à Kalimbè certaines informations, incluant, sans que cela soit limitatif, une adresse e-mail valide (vos « Informations »).</p>
                      <p>Tout profil que vous soumettez doit être exact et vous décrire en tant qu’individu. Les profils nécessitent de remplir des champs standard. Vous pouvez ne pas inclure dans ces profils des numéros de téléphone, adresses postales, permettant de vous contacter autre que votre nom de famille et vos URL.</p>
                      <p>Vous êtes seul responsable du format, du contenu et de l’exactitude de tout CV ou élément mis en ligne sur les sites Kalimbè.</p>
                      <p>Kalimbè se réserve le droit de proposer des services et produits provenant de tiers suivant les préférences que vous aurez indiquées lors de votre inscription ou ultérieurement et si vous avez accepté de recevoir les offres provenant de Kalimbè ou de tiers.</p>
                      <p>Vous ne détenez aucun droit de propriété sur votre compte. Si vous fermez votre compte ou si votre compte est supprimé par Kalimbè par suite d’une utilisation abusive de votre part, toutes vos informations, y compris celles du profil, des CV, des lettres, emplois enregistrés et questionnaires pourront être supprimés de la base de données de Kalimbè et enlevés du domaine public des sites de Kalimbè. Des données peuvent toutefois subsister pour une certaine période en raison du délai de traitement nécessaire à leur suppression. Il est précisé que des tiers peuvent conserver des copies sauvegardées de vos données personnelles.</p>
                      <p>Kalimbè se réserve le droit de supprimer votre compte Client et toutes vos Données après une période significative d’inactivité.</p>
                     
                      <h5 id="information">4. Contenu utilisateur et Soumissions.</h5>
                      <p>Toute information, donnée, texte, logiciel, musique, son, photo, graphique, vidéo ou autre matériels soumis ou publié (« contenu utilisateur ») sur les sites de Kalimbè est sous votre seule responsabilité. Kalimbè est déchargée de toute responsabilité relative à la propriété du contenu utilisateur ou son contrôle. Vous, ou les tiers affiliés restez les seuls détenteurs de tous les brevets, marques commerciales et droits d’auteurs sur les contenus utilisateur que vous publiez sur ou par l’intermédiaire des sites de Kalimbè. Il est de votre responsabilité de protéger ces droits. En soumettant ou en publiant du contenu sur ou par l’intermédiaire de Kalimbè, vous accordez à cette dernière un droit mondial, non exclusif, transférable, sous-licenciable et gratuit pour utiliser, reproduire, adapter, répandre, publier ces contenus. En outre, par la soumission ou la publication d’un contenu accessible au public, vous accordez à Kalimbè un droit mondial non exclusif et gratuit pour reproduire, adapter, modifier, distribuer et publier ces contenus dans le but de promouvoir Kalimbè et ses services. Après la suppression du Contenu par l’utilisateur, Kalimbè cessera l’utilisation dudit contenu dans un délai raisonnable. Kalimbè se réserve, à sa seule discrétion, le droit de refuser de publier, d’afficher ou de transmettre du contenu utilisateur.</p>
                      <p>Vous déclarez et garantissez que vous avez légalement obtenu tous les droits d’exploitation des licences relatives au contenu publié. En soumettant du Contenu dans une partie publique du site Kalimbè, vous accordez à tout utilisateur le droit d’accéder, d’afficher, de consulter, de conserver et de reproduire tel contenu à des fins personnelles. Sous réserve de ce qui précède, le propriétaire de ce Contenu conserve tous les droits qui peuvent exister sur le contenu publié. Kalimbè se réserve le droit de réviser et/ou retirer tout contenu utilisateur qui, de son avis, enfreint les présentes conditions d’utilisation, enfreint les lois et règlements en vigueur, est abusif, dérangeant, vulgaire, illicite ou porte atteinte aux droits de tiers, préjudicie ou menace la sécurité des autres utilisateurs.</p>
                      <p>Kalimbè ne garantit pas la véracité, l’exactitude ou la fiabilité du contenu utilisateur ou message posté par les utilisateurs. Kalimbè n’endosse pas les opinions éventuellement émises par ces utilisateurs. L’utilisateur reconnait que le crédit à accorder au contenu affiché par d’autres utilisateurs est de sa seule responsabilité.</p>
                      <p>Ce qui suit est une liste partielle de contenu interdit sur les Sites ou Applications. Ainsi, sans que cette liste soit exhaustive, sont interdits les contenus :</p>
                      <p>Offensant ou qui implicitement ou explicitement promouvraient, encourageraient ou cautionneraient le racisme, le sectarisme, la discrimination, la haine ou la violence physique de toute nature contre un groupe ou une personne ;</p>
                      <p>Incitant ou prônant le harcèlement de tout groupe ou individu ;</p>
                      <p>S’apparentant à du «Junk mail», «chaînes de lettres», de publipostage non sollicité, « spamming » ou « phishing » ;</p>
                      <p>Encourageant ou soutenant des informations fausses, trompeuses, des activités illégales ou des comportements injurieux, menaçants, obscènes, diffamatoires ou calomnieux ;</p>
                      <p>Encourageant ou endossant la copie illégale ou non autorisée d’œuvres protégées de tiers (telles que musique, programmes informatiques, vidéos ou autres médias) en fournissant ou mettant à disposition ces œuvres ou des liens vers eux ou en fournissant des solutions de contournement des protections de ces œuvres ou des liens vers de telles solutions ;</p>
                      <p>Contenant des restrictions d’accès par mot de passe ou des pages ou images cachées ;</p>
                      <p>Présentant, ou incluant des liens vers, du contenu de toute nature à caractère pornographique, indécent, sexuellement explicite, violent ou, plus généralement, contraire aux bonnes mœurs ;</p>
                      <p>Présentant, ou incluant des liens vers, des sites tiers exploitant des mineurs, ou leurs images, quelles qu’elles soient ;</p>
                      <p>Fournissant des instructions sur des activités illégales ou illicites, que ce soit en vertu des lois et règlements ou en vertu des présentes, en ce compris notamment la fabrication ou l’achat d’armes, la violation de la vie privée, la fourniture ou la création de virus informatiques ou le piratage informatique;</p>
                      <p>Sollicitant la transmission des mots de passe et/ou informations personnelles des autres utilisateurs.</p>
                      <p>Tout Profil que vous mettez en ligne doit vous correspondre. Sont interdites les descriptions ne correspondant pas à votre personne, tel que notamment animaux, lieux, objets, personnages de fiction ou personnes réelles autres que vous.</p>
                      <p>Il est interdit d’incorporer dans le contenu publié sur le Networking Kalimbè, des données qui peuvent être interprétées comme une sollicitation directe, une annonce ou un recrutement pour un poste disponible ciblant les personnes recherchant un emploi soit à temps plein ou partiel. Afin de protéger notre communauté d’utilisateurs des publicités ou sollicitations intempestives, Kalimbè se réserve le droit de limiter la quantité de mails ou autres messages qu’un utilisateur peut envoyer aux utilisateurs.</p>
                      <p>Du contenu extrait des Profils peut aussi être rendu disponible sur les sites de Kalimbè. Kalimbè ne garantit aucunement la valeur ou l’exactitude de tels extraits ou de leur pertinence pour une évaluation par les employeurs. Ces Profils dérivés peuvent varier du Contenu original de l’utilisateur.</p>

                     
                      <h5 id="security">5. Notifications relatives aux Droits d’auteur ou des marques.</h5>
                      <p>Si vous constatez que des éléments publiés sur l’un quelconque des sites de Kalimbè portent atteinte à des droits d’auteur ou autres droits protégés, merci de contacter Kalimbè par à l’adresse contact@kalimbe.com</p>
                     

                      <h5 id="update">6. Résiliation pour infraction aux droits de la propriété intellectuelle d’autrui.</h5>
                      <p>Kalimbè respecte les droits de propriété intellectuelle des tiers et nous demandons à nos utilisateurs, titulaires de comptes et partenaires de contenu d’en faire autant. La reproduction, copie, distribution, modification, représentation ou diffusion au public non autorisées d’œuvres protégées par le droit d’auteur, constitue une violation des droits du titulaire.</p>
                      <p>Nonobstant ce qui précède, si de bonne foi, vous pensez que la suppression de compte a été faite sur des bases injustifiées, nous vous prions de contacter Kalimbè comme indiqué ci-dessus en article 6.</p>
                     
                      <h5 id="update">7. La Responsabilité de Kalimbè.</h5>
                      <p>Les sites Kalimbè sont uniquement des lieux d’échanges permettant (i) aux employeurs d’afficher des offres d’emploi et recherchées des candidats et (ii) aux candidats de publier leurs CV et profils et rechercher un emploi.</p>
                      <p>En conséquence, Kalimbè n’exerce aucun contrôle sur la qualité, la sécurité ou la légalité des emplois ou CV affichés, la véracité ou la précision des rubriques, la capacité des employeurs à offrir des emplois aux candidats ou l’aptitude des candidats à pourvoir aux positions proposées. Bien que Kalimbè se réserve le droit, à tout moment et à sa seule discrétion de retirer tout contenu utilisateur, offre d’emploi, CV ou autre élément publié sur ses sites, Kalimbè n’assume sur ce point aucune obligation, sous réserve toutefois des obligations légales impératives, et rejette toute responsabilité pour ne pas avoir supprimé quelques éléments publiés sur son site.</p>
                      <p>Nous attirons votre attention sur la présence de risques (pouvant aller jusqu’au risque de préjudice corporel) qui pourrait résulter de contact avec des étrangers, des mineurs ou des gens qui utilisent de fausses identités. Vous assumez tous les risques qui résultent des relations avec d’autres utilisateurs avec lesquels vous entrez en contact sur les sites de Kalimbè. Des informations sur d’autres personnes peuvent être offensantes, blessantes ou inexactes. Dans certains cas, vous pouvez être présenté de façon erronée ou mensongère. Nous nous attendons à ce que vous soyez prudent et raisonnable quand vous utilisez les sites de Kalimbè.</p>
                      <p>Comme l’identification d’utilisateurs est difficile sur Internet, Kalimbè ne saurait garantir que chaque utilisateur correspond à ce qu’il prétend être. De la même manière que nous ne sommes, ni ne pouvons être, partie aux échanges entre des utilisateurs, nous ne contrôlons pas le comportement des participants sur les sites Kalimbè. En cas de litige avec un ou plusieurs utilisateurs, vous déchargez expressément Kalimbè (nos agents et employés) de toute demande, réclamation et dommages (dommages consécutifs effectifs, directs ou indirects) de tout type et de toute nature, connue ou inconnue, dommages soupçonnés ou insoupçonnés, dommages révélés et non révélés qui résulteraient du comportement ou de la tromperie d’un utilisateur.</p>

                      <h5 id="update">8. Exclusion de garantie.</h5>
                      <p>Sous réserve de lois d’ordre public contraires, Kalimbè n’est aucunement responsable des dysfonctionnements de ses sites, de ses services, d’éventuels virus ou autre mécanisme dommageable. Kalimbè ne saurait être tenue pour responsable des couts liés à d’éventuels remplacements d’équipements, mesures de remise en état, restaurations de données ou autres évènements liés à votre utilisation des sites kalimbè ou de leur contenu.</p>
                      
                      <h5 id="update">9. Exclusion de garantie pour dommages consécutifs.</h5>
                      <p>Sous réserve de dispositions de lois d’ordre public contraires, kalimbè, ses fournisseurs ou tout tiers mentionné sur quelque site de Kalimbè ne sauraient en aucun cas voir sa responsabilité engagée pour tout dommage, quel qu’il soit (en ce compris notamment les dommages incidents, consécutifs, pertes d’une chance, pertes de profit ou de données ou encore interruption de business) résultant de l’utilisation ou de l’incapacité d’utiliser tout ou partie du site Kalimbè et ses contenus, que l’on se base pour une réclamation sur une garantie, un contrat, une manipulation non autorisée ou une autre raison légale et que Kalimbè soit ou non informé de tels dommages.</p>
                      
                      <h5 id="update">10. Liens vers d’autres sites.</h5>
                      <p>Les sites de Kalimbè comprennent des liens vers des sites tiers. Ces liens ne sont fournis que pour vous aider et Kalimbè n’en cautionne pas les contenus et ne saurait être associée d’une quelconque manière à ces sites. Kalimbè ne saurait être tenue pour responsable desdits sites et ne garantit dès lors ni leur contenu ni leur fiabilité. Si vous accédez à ces sites tiers, vous le faites à vos risques et périls.</p>
                      
                      <h5 id="update">11. Pas de revente ou d’autre utilisation commerciale non autorisée.</h5>
                      <p>Vous vous engagez à ne pas vendre ou céder vos droits et obligations dans le cadre des présentes conditions. Vous vous engagez également à ne faire aucune utilisation commerciale non autorisée de tout ou partie des sites Kalimbè.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

@endsection